// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/scout.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScoutService_CreateGame_FullMethodName = "/scout.ScoutService/CreateGame"
	ScoutService_Step_FullMethodName       = "/scout.ScoutService/Step"
)

// ScoutServiceClient is the client API for ScoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScoutServiceClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
}

type scoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoutServiceClient(cc grpc.ClientConnInterface) ScoutServiceClient {
	return &scoutServiceClient{cc}
}

func (c *scoutServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, ScoutService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoutServiceClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, ScoutService_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoutServiceServer is the server API for ScoutService service.
// All implementations must embed UnimplementedScoutServiceServer
// for forward compatibility.
type ScoutServiceServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	Step(context.Context, *StepRequest) (*StepResponse, error)
	mustEmbedUnimplementedScoutServiceServer()
}

// UnimplementedScoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScoutServiceServer struct{}

func (UnimplementedScoutServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedScoutServiceServer) Step(context.Context, *StepRequest) (*StepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedScoutServiceServer) mustEmbedUnimplementedScoutServiceServer() {}
func (UnimplementedScoutServiceServer) testEmbeddedByValue()                      {}

// UnsafeScoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoutServiceServer will
// result in compilation errors.
type UnsafeScoutServiceServer interface {
	mustEmbedUnimplementedScoutServiceServer()
}

func RegisterScoutServiceServer(s grpc.ServiceRegistrar, srv ScoutServiceServer) {
	// If the following call panics, it indicates UnimplementedScoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScoutService_ServiceDesc, srv)
}

func _ScoutService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoutService_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScoutService_ServiceDesc is the grpc.ServiceDesc for ScoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scout.ScoutService",
	HandlerType: (*ScoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _ScoutService_CreateGame_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _ScoutService_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scout.proto",
}
