// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/scout.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumPlayers    int32                  `protobuf:"varint,1,opt,name=num_players,json=numPlayers,proto3" json:"num_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_proto_scout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_scout_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetNumPlayers() int32 {
	if x != nil {
		return x.NumPlayers
	}
	return 0
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_proto_scout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_scout_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type StepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Action        int32                  `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_proto_scout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_proto_scout_proto_rawDescGZIP(), []int{2}
}

func (x *StepRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StepRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type StepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_proto_scout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_proto_scout_proto_rawDescGZIP(), []int{3}
}

func (x *StepResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_proto_scout_proto protoreflect.FileDescriptor

const file_proto_scout_proto_rawDesc = "" +
	"\n" +
	"\x11proto/scout.proto\x12\x05scout\"4\n" +
	"\x11CreateGameRequest\x12\x1f\n" +
	"\vnum_players\x18\x01 \x01(\x05R\n" +
	"numPlayers\"-\n" +
	"\x12CreateGameResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\">\n" +
	"\vStepRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\x05R\x06action\"\"\n" +
	"\fStepResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done2\x82\x01\n" +
	"\fScoutService\x12A\n" +
	"\n" +
	"CreateGame\x12\x18.scout.CreateGameRequest\x1a\x19.scout.CreateGameResponse\x12/\n" +
	"\x04Step\x12\x12.scout.StepRequest\x1a\x13.scout.StepResponseB\x16Z\x14scout-ai/proto;protob\x06proto3"

var (
	file_proto_scout_proto_rawDescOnce sync.Once
	file_proto_scout_proto_rawDescData []byte
)

func file_proto_scout_proto_rawDescGZIP() []byte {
	file_proto_scout_proto_rawDescOnce.Do(func() {
		file_proto_scout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scout_proto_rawDesc), len(file_proto_scout_proto_rawDesc)))
	})
	return file_proto_scout_proto_rawDescData
}

var file_proto_scout_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scout_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: scout.CreateGameRequest
	(*CreateGameResponse)(nil), // 1: scout.CreateGameResponse
	(*StepRequest)(nil),        // 2: scout.StepRequest
	(*StepResponse)(nil),       // 3: scout.StepResponse
}
var file_proto_scout_proto_depIdxs = []int32{
	0, // 0: scout.ScoutService.CreateGame:input_type -> scout.CreateGameRequest
	2, // 1: scout.ScoutService.Step:input_type -> scout.StepRequest
	1, // 2: scout.ScoutService.CreateGame:output_type -> scout.CreateGameResponse
	3, // 3: scout.ScoutService.Step:output_type -> scout.StepResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_scout_proto_init() }
func file_proto_scout_proto_init() {
	if File_proto_scout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scout_proto_rawDesc), len(file_proto_scout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scout_proto_goTypes,
		DependencyIndexes: file_proto_scout_proto_depIdxs,
		MessageInfos:      file_proto_scout_proto_msgTypes,
	}.Build()
	File_proto_scout_proto = out.File
	file_proto_scout_proto_goTypes = nil
	file_proto_scout_proto_depIdxs = nil
}
