// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/scout.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScoutService_CreateGame_FullMethodName     = "/scout.ScoutService/CreateGame"
	ScoutService_PlayerAction_FullMethodName   = "/scout.ScoutService/PlayerAction"
	ScoutService_GetGameState_FullMethodName   = "/scout.ScoutService/GetGameState"
	ScoutService_GetPlayerState_FullMethodName = "/scout.ScoutService/GetPlayerState"
)

// ScoutServiceClient is the client API for ScoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScoutServiceClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	PlayerAction(ctx context.Context, in *PlayerActionRequest, opts ...grpc.CallOption) (*PlayerActionResponse, error)
	GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error)
	GetPlayerState(ctx context.Context, in *GetPlayerStateRequest, opts ...grpc.CallOption) (*GetPlayerStateResponse, error)
}

type scoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoutServiceClient(cc grpc.ClientConnInterface) ScoutServiceClient {
	return &scoutServiceClient{cc}
}

func (c *scoutServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, ScoutService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoutServiceClient) PlayerAction(ctx context.Context, in *PlayerActionRequest, opts ...grpc.CallOption) (*PlayerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerActionResponse)
	err := c.cc.Invoke(ctx, ScoutService_PlayerAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoutServiceClient) GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStateResponse)
	err := c.cc.Invoke(ctx, ScoutService_GetGameState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoutServiceClient) GetPlayerState(ctx context.Context, in *GetPlayerStateRequest, opts ...grpc.CallOption) (*GetPlayerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerStateResponse)
	err := c.cc.Invoke(ctx, ScoutService_GetPlayerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoutServiceServer is the server API for ScoutService service.
// All implementations must embed UnimplementedScoutServiceServer
// for forward compatibility.
type ScoutServiceServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	PlayerAction(context.Context, *PlayerActionRequest) (*PlayerActionResponse, error)
	GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error)
	GetPlayerState(context.Context, *GetPlayerStateRequest) (*GetPlayerStateResponse, error)
	mustEmbedUnimplementedScoutServiceServer()
}

// UnimplementedScoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScoutServiceServer struct{}

func (UnimplementedScoutServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedScoutServiceServer) PlayerAction(context.Context, *PlayerActionRequest) (*PlayerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerAction not implemented")
}
func (UnimplementedScoutServiceServer) GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameState not implemented")
}
func (UnimplementedScoutServiceServer) GetPlayerState(context.Context, *GetPlayerStateRequest) (*GetPlayerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerState not implemented")
}
func (UnimplementedScoutServiceServer) mustEmbedUnimplementedScoutServiceServer() {}
func (UnimplementedScoutServiceServer) testEmbeddedByValue()                      {}

// UnsafeScoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoutServiceServer will
// result in compilation errors.
type UnsafeScoutServiceServer interface {
	mustEmbedUnimplementedScoutServiceServer()
}

func RegisterScoutServiceServer(s grpc.ServiceRegistrar, srv ScoutServiceServer) {
	// If the following call panics, it indicates UnimplementedScoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScoutService_ServiceDesc, srv)
}

func _ScoutService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoutService_PlayerAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).PlayerAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_PlayerAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).PlayerAction(ctx, req.(*PlayerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoutService_GetGameState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).GetGameState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_GetGameState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).GetGameState(ctx, req.(*GetGameStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoutService_GetPlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).GetPlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_GetPlayerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).GetPlayerState(ctx, req.(*GetPlayerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScoutService_ServiceDesc is the grpc.ServiceDesc for ScoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scout.ScoutService",
	HandlerType: (*ScoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _ScoutService_CreateGame_Handler,
		},
		{
			MethodName: "PlayerAction",
			Handler:    _ScoutService_PlayerAction_Handler,
		},
		{
			MethodName: "GetGameState",
			Handler:    _ScoutService_GetGameState_Handler,
		},
		{
			MethodName: "GetPlayerState",
			Handler:    _ScoutService_GetPlayerState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scout.proto",
}
